### ISSUE TITLE
Quality Problems with Mipmaps

### ISSUE THREAD

**Issue by ptasev** [Nominom/BCnEncoder.NET#10]
I have a BC3 image that I decoded with my own decoders. I'm not sure how the original BC3 image was created (maybe with nvidia texture tools?). Once I decoded the main mip from the image, I encoded it again to BC3 using your library. Then I decoded the newly encoded image again (with my own decoder), and I noticed that there are issues/differences in how the smaller mip levels look.

I have attached the original images in the expected folder, and the new images using your encoder in the actual folder. I used the following code to encode the images:

```csharp
BcEncoder encoder = new BcEncoder();
encoder.OutputOptions.generateMipMaps = true;
encoder.OutputOptions.quality = CompressionQuality.BestQuality;
encoder.OutputOptions.fileFormat = OutputFileFormat.Dds;
encoder.OutputOptions.format = CompressionFormat.BC3;
encoder.OutputOptions.ddsBc1WriteAlphaFlag = false;
encoder.OutputOptions.maxMipMapLevel = 5;

Image<Rgba32> faceImage = ...;
var encodedData = encoder.EncodeToRawBytes(faceImage);
```

[mipmap.zip](https://github.com/Nominom/BCnEncoder.NET/files/5712620/mipmap.zip)

**Comment by Nominom** [comment]
I'll look into it.

**Comment by Nominom** [comment]
Hey,

Sorry that this took so long, but I've looked into it a little more closely now and it seems that the difference in mipmaps stems from the resizing algorithm used. Most likely whatever program encoded the original image was using a nearest-neighbor-style resizing algorithm, while mine uses ImageSharp's default resizing function (which probably uses some kinda blending of pixels). 

For what it's worth, the mip3 in the expected output folder has way more beige and brown colors than the original image in the corresponding spots, while the colors look more accurate proportionately in BcnEncoder's output.

I think adding an option in the encoder for which resizing algorithm to use could be something beneficial, but it doesn't seem like a too big of a problem for now.

**Comment by ptasev** [comment]
No worries, thanks for looking into this.  I guess it's just odd to me that there's such huge black bands after a resize from 64x64 to 32x32.  I see now that it is due to ImageSharp.

I guess it's easy enough to try my own resizing techniques and feed each mip separately into your encoder for now.

**Comment by Nominom** [comment]
Seems like the ImageSharp team might add the option for resizing the image with non-premultiplied alpha based on your issue. I can add the option to the encoder once they update the package.

**Comment by Nominom** [comment]
Hey, since ImageSharp is not used for resizing in 2.0.0, would you like to try and see if this is still an issue in the new version?

**Comment by ptasev** [comment]
There's a bug in MipMapper.cs in loop at line 85.  If the `maxNumMipMaps` is a number such that `mipWidth` or `mipHeight` do not become one, then the output remains 0. This in turn causes `result` at line 37 to be an empty array.

Also, I'm wondering if the statement `mipWidth == 1 && mipHeight == 1`, it should use `||` not `&&`. Although this may be a moot point if the method has to be rewritten in a different way.

**Comment by Nominom** [comment]
Ah, you're correct. I'll fix it today.

I'm not sure if it should be ||, since that would mean the last mip might be something else than 1x1. I guess I could check how other encoders handle tall or wide textures.

A bit of a shame that we switched off of ImageSharp right when they added this, but at least they now have the feature if someone needs it.

**Comment by Nominom** [comment]
New version is up in nuget with a fix.

**Comment by ptasev** [comment]
Looks like the problem has been fixed. Thanks!
