### ISSUE TITLE
Change Marshal.SizeOf to Unsafe.SizeOf

### ISSUE THREAD

**Issue by Nominom** [Nominom/BCnEncoder.NET#12]
This currently doesn't break anything but Unsafe.SizeOf is the correct way to do it.

**Comment by onepiecefreak3** [comment]
What is the difference between Marshal.SizeOf and Unsafe.SizeOf that makes Unsafe.SizeOf the "correct" way to do it?

**Comment by Nominom** [comment]
They both produce the same result in most cases. Seems like Marshal.SizeOf is intended for when sending raw data between C# and C/C++, while Unsafe.SizeOf is for internal C# use. The "marshal" can add padding bytes sometimes if necessary. At least this is what I remember reading.

**Comment by Nominom** [comment]
This was fixed in the latest commit already though.
