### ISSUE TITLE
Upload this code to nuget.org

### ISSUE THREAD

**Issue by onepiecefreak3** [Nominom/BCnEncoder.NET#13]
As the title suggests, this project would be a pretty good addition to nuget.

**Comment by Nominom** [comment]
Hey, it's already there. :) https://www.nuget.org/packages/BCnEncoder.Net/

**Comment by onepiecefreak3** [comment]
Oh interesting. Then it would be a real nice addition to refer to it in the READ.ME

**Comment by Nominom** [comment]
There's a lil' button next to the "tests passing" icon. I could add a more visible link somewhere else in the readme too.

**Comment by onepiecefreak3** [comment]
Yh, I totally glimpsed over it. Most of those badges are mostly code coverage and passing test badges.
I never knew there was for nugets, and therefore didn't look for that. Sorry for this stupid issue then.
