### ISSUE TITLE
Progress report

### ISSUE THREAD

**Issue by onepiecefreak3** [Nominom/BCnEncoder.NET#15]
Would it be a desirable feature to add report progress for encoding and decoding processes? For longer running processes like best quality compression, this might be helpful if the library is used for GUI's.

There already are build-in types in .NET like ``IProgress<T>``. And maybe the progress reporter can be part of the decoder/encoder options.

**Comment by Nominom** [comment]
Would adding such an option require adding async public api methods as well? I have not used IProgress<T> before but updating the progress in the encoding methods by blocksProcessed/totalBlocks is probably trivial to add.

**Comment by onepiecefreak3** [comment]
Yes it would be trivial indeed. And no, I think it wouldn't need async at all. However for seeing how long compression processes can take, wouldn't it make sense to add async calls either way?

**Comment by Nominom** [comment]
If you want to add it (and possibly async api) you have my blessing. 

I pushed a few tests, code changes and some more raw api methods so you might want to pull the latest version. There's now a BaseBcBlockEncoder similar to the one you added for decoders, so adding the progress reporting should be easier to do as well.

**Comment by onepiecefreak3** [comment]
Ah yes, I tried to do a BaseBcBlockEncoder, but the encoding side of things is way over my head, so I left it like it was before I break too much beyond repair on my end.
And thx, I will get to work on the progress first. The async api probably needs a bit more designing on my part to look good enough. I will create another issue for the async api.

**Comment by Nominom** [comment]
Sounds good.

**Comment by onepiecefreak3** [comment]
PR #24 adds the aforementioned progress context.
