### ISSUE TITLE
Support for ATC

### ISSUE THREAD

**Issue by onepiecefreak3** [Nominom/BCnEncoder.NET#17]
ATC is a rather exotic derivation of DXT, but it exists. I first encountered it on my work for Dai Gyakuten Saiban Mobile. Depending on the phone, the engine chose a certain image from the internal image format. And those image formats contained an encoding similar to DXT, but with slight variations.

ATC is supported in hardware by Adreno mobile GPU's (and that's where probably the name comes from, Adreno Texture Compression) and as said above, is a derivation of DXT. Here's a document detailing the differences between ATC and DXT, and how to easily convert DXT to ATC and vice versa.
http://www.guildsoftware.com/papers/2012.Converting.DXTC.to.ATC.pdf

I think it would be a nice addition, even though ATC is not that widespread.
(I already have a working implementation of ATC, so I can probably provide that one within the next week)

**Comment by Nominom** [comment]
Never heard of ATC before taking a peek at your kuriimu project. Is there a dds or ktx format enum for it, or is it packaged in a different file type completely?

I think having it supported wouldn't hurt at least. Even if no-one ends up needing it.

**Comment by onepiecefreak3** [comment]
That's an interesting question. I didn't find it before anywhere, so it is possible to not have one.

**Comment by onepiecefreak3** [comment]
It seems there is: https://www.khronos.org/registry/OpenGL/extensions/AMD/AMD_compressed_ATC_texture.txt

**Comment by Nominom** [comment]
Seems like dds is also (hackily?) supported. The official Adreno texture tool says the following:

> 
> For each compression type, the DDS file is output using the following four-character code (dwFourCC):
> 
> ATC RGBA Explicit = "ATCI"
> ATC RGBA Interpolated = "ATCA"
> ATC RGB = "ATC "
> ETC1 RGB8 = "ETC1"
> 3DC X = "3DC1"
> 3DC XY = "3DC

There's no official enum for it in the Microsoft docs though.

**Comment by onepiecefreak3** [comment]
Well, it is exotic nonetheless. If one searches explicitly for it, it gets exceedingly easier to find it. But it's by far not widespread enough. Maybe that's the reason for microsoft not documenting it at all?

**Comment by Nominom** [comment]
Might be that Microsoft did not intend to support it, and the adreno team just came up with a way to say that "hey, this texture is ATC encoded" by writing it in the dwFourCC. Nevertheless, if we do the same it should work just fine.

**Comment by onepiecefreak3** [comment]
PR #21 is merged and this issue can be closed.
