### ISSUE TITLE
Bc4 & Bc5 decoding

### ISSUE THREAD

**Issue by Nominom** [Nominom/BCnEncoder.NET#18]
After PR #14 the issue #3 is now fixed in Bc1, 2 and 3. Bc4, Bc5 and the alpha block in Bc3 still seem to have some issues.

Currently investigating what's up.

**Comment by onepiecefreak3** [comment]
Do they use different interpolations? I thought I implemented the interpolation everywhere.
How did you notice there are problems?

**Comment by Nominom** [comment]
The new interpolation is used everywhere. I compared the output to compressonator again and there is a 1-bit error in some pixels. I'll write some more tests today and investigate further.

**Comment by onepiecefreak3** [comment]
Hmm, curious. And they can't be encoding artifacts?
I was sure that the interpolation was modeled after what compressonator already uses.

**Comment by Nominom** [comment]
It is specifically while decoding, so the output should be identical. Might be a different problem too (like indices not set correctly or something).

**Comment by Nominom** [comment]
Now I'm confused. Compressonator seems to add a +3 to the value before dividing it.
```
// bcn_common_kernel.h
static void cmp_getCompressedAlphaRampS(CGU_INT8 alpha[8], const CGU_UINT32 compressedBlock[2])
{
    alpha[0] = (CGU_INT8)(compressedBlock[0] & 0xff);
    alpha[1] = (CGU_INT8)((compressedBlock[0] >> 8) & 0xff);

    if (alpha[0] > alpha[1])
    {
        // 8-alpha block:  derive the other six alphas.
        // Bit code 000 = alpha_0, 001 = alpha_1, others are interpolated.
#ifdef ASPM_GPU
        alpha[2] = (CGU_UINT8)((6 * alpha[0] + 1 * alpha[1] + 3) / 7);  // bit code 010
        alpha[3] = (CGU_UINT8)((5 * alpha[0] + 2 * alpha[1] + 3) / 7);  // bit code 011
        alpha[4] = (CGU_UINT8)((4 * alpha[0] + 3 * alpha[1] + 3) / 7);  // bit code 100
        alpha[5] = (CGU_UINT8)((3 * alpha[0] + 4 * alpha[1] + 3) / 7);  // bit code 101
        alpha[6] = (CGU_UINT8)((2 * alpha[0] + 5 * alpha[1] + 3) / 7);  // bit code 110
        alpha[7] = (CGU_UINT8)((1 * alpha[0] + 6 * alpha[1] + 3) / 7);  // bit code 111
#else
        alpha[2] = static_cast<CGU_UINT8>((6 * alpha[0] + 1 * alpha[1] + 3) / 7);  // bit code 010
        alpha[3] = static_cast<CGU_UINT8>((5 * alpha[0] + 2 * alpha[1] + 3) / 7);  // bit code 011
        alpha[4] = static_cast<CGU_UINT8>((4 * alpha[0] + 3 * alpha[1] + 3) / 7);  // bit code 100
        alpha[5] = static_cast<CGU_UINT8>((3 * alpha[0] + 4 * alpha[1] + 3) / 7);  // bit code 101
        alpha[6] = static_cast<CGU_UINT8>((2 * alpha[0] + 5 * alpha[1] + 3) / 7);  // bit code 110
        alpha[7] = static_cast<CGU_UINT8>((1 * alpha[0] + 6 * alpha[1] + 3) / 7);  // bit code 111
#endif
    }
    else
    {
        // 6-alpha block.
        // Bit code 000 = alpha_0, 001 = alpha_1, others are interpolated.
#ifdef ASPM_GPU
        alpha[2] = (CGU_UINT8)((4 * alpha[0] + 1 * alpha[1] + 2) / 5);  // Bit code 010
        alpha[3] = (CGU_UINT8)((3 * alpha[0] + 2 * alpha[1] + 2) / 5);  // Bit code 011
        alpha[4] = (CGU_UINT8)((2 * alpha[0] + 3 * alpha[1] + 2) / 5);  // Bit code 100
        alpha[5] = (CGU_UINT8)((1 * alpha[0] + 4 * alpha[1] + 2) / 5);  // Bit code 101
#else
        alpha[2] = static_cast<CGU_UINT8>((4 * alpha[0] + 1 * alpha[1] + 2) / 5);  // Bit code 010
        alpha[3] = static_cast<CGU_UINT8>((3 * alpha[0] + 2 * alpha[1] + 2) / 5);  // Bit code 011
        alpha[4] = static_cast<CGU_UINT8>((2 * alpha[0] + 3 * alpha[1] + 2) / 5);  // Bit code 100
        alpha[5] = static_cast<CGU_UINT8>((1 * alpha[0] + 4 * alpha[1] + 2) / 5);  // Bit code 101
#endif
        alpha[6] = -128;  // Bit code 110
        alpha[7] = 127;   // Bit code 111
    }
}
```

**Comment by onepiecefreak3** [comment]
Hmm. Maybe compressonator adds ``(int)(den/2)`` for some kind of error correction?

**Comment by Nominom** [comment]
[Microsoft docs](https://docs.microsoft.com/en-us/windows/win32/direct3d10/d3d10-graphics-programming-guide-resources-block-compression#bc5_unorm) shows an example code for the interpolation as the following:

```
unsigned word red_0, red_1;

if( red_0 > red_1 )
{
  // 6 interpolated color values
  red_2 = (6*red_0 + 1*red_1)/7.0f; // bit code 010
  red_3 = (5*red_0 + 2*red_1)/7.0f; // bit code 011
  red_4 = (4*red_0 + 3*red_1)/7.0f; // bit code 100
  red_5 = (3*red_0 + 4*red_1)/7.0f; // bit code 101
  red_6 = (2*red_0 + 5*red_1)/7.0f; // bit code 110
  red_7 = (1*red_0 + 6*red_1)/7.0f; // bit code 111
}
else
{
  // 4 interpolated color values
  red_2 = (4*red_0 + 1*red_1)/5.0f; // bit code 010
  red_3 = (3*red_0 + 2*red_1)/5.0f; // bit code 011
  red_4 = (2*red_0 + 3*red_1)/5.0f; // bit code 100
  red_5 = (1*red_0 + 4*red_1)/5.0f; // bit code 101
  red_6 = 0.0f;                     // bit code 110
  red_7 = 1.0f;                     // bit code 111
}
```
The Khronos data format also defines it without any addition.

The 3 part division seen in #3 does not have +1, so I'm not sure what's going on.

**Comment by Nominom** [comment]
I tried floating point interpolation and it did not match.  I added the +3 and +2 and it matched. 

Maybe the addition is useful for something. Paint.NET also produces an identical output to Compressonator.

**Comment by onepiecefreak3** [comment]
So, we either have to believe the documentation, or the implementation. Tough choice.

**Comment by onepiecefreak3** [comment]
I opened an issue on compressonator https://github.com/GPUOpen-Tools/compressonator/issues/159. Hopefully they answer.

**Comment by Nominom** [comment]
> I opened an issue on compressonator [GPUOpen-Tools/compressonator#159](https://github.com/GPUOpen-Tools/compressonator/issues/159). Hopefully they answer.

Saying "uses compressonator as a reference" sounds almost like "we copied your code". Might want to change it to something like "uses the output of compressonator as a reference and we noticed this is implemented differently"

**Comment by onepiecefreak3** [comment]
Sure thing. I changed that.

**Comment by onepiecefreak3** [comment]
Well, according to the response, adding those consts indeed increases accuracy when working on integers. It seems that the documented method is used if we the resulting value is float and used as such. That's what I get from it.

**Comment by Nominom** [comment]
Alright, I'll also push my tests later.

**Comment by onepiecefreak3** [comment]
Can this issue be closed now?

**Comment by Nominom** [comment]
Ah, yes. The tests are added and they pass.
