### ISSUE TITLE
Incorrectly calculating byte size of dds mip in certain cases

### ISSUE THREAD

**Issue by ptasev** [Nominom/BCnEncoder.NET#25]
It seems the dds file loader assumes that pitch is always stored in place of the header field `pitchOrLinearSize`. This fails when linear size is stored since the computation essentially becomes `width * height * height` which can result in a number larger than int.Max that arrays support.

https://github.com/Nominom/BCnEncoder.NET/blob/master/BCnEnc.Net/Shared/DdsFile.cs#L80

**Comment by onepiecefreak3** [comment]
How can this be resolved? Is there some flag that tells the consumer if the content is pitch or linear size?

**Comment by onepiecefreak3** [comment]
It seems that dwFlags contains a flag denoting linear size or pitch. I investigate that further.

**Comment by ptasev** [comment]
An alternative could be to not rely on that field, and instead replace the code with something like this (rely on format to get byte size):

```csharp
if (!dxt10Format)
{
    if (header.ddsPixelFormat.IsDxt1To5CompressedFormat)
    {
        if (header.ddsPixelFormat.DxgiFormat == DxgiFormat.DxgiFormatBc1Unorm)
        {
            sizeInBytes *= 8;
        }
        else
        {
            sizeInBytes *= 16;
        }
    }
    else
    {
        sizeInBytes = (uint)(sizeInBytes * header.ddsPixelFormat.DxgiFormat.GetByteSize());
    }
}
else
{
    sizeInBytes = (uint)(sizeInBytes * dxt10Header.dxgiFormat.GetByteSize());
}
```

**Comment by Nominom** [comment]
This is good to know. I'll add a test case for this.

**Comment by onepiecefreak3** [comment]
I see. To get this code a bit more performant I replace the division by 4 to pad width and height by ``& ~3``.
Resulting in ``(n + 3) & ~3`` to pad on 4.

**Comment by ptasev** [comment]
It probably doesn't matter too much in this code, but it may be beneficial here:

https://github.com/Nominom/BCnEncoder.NET/blob/master/BCnEnc.Net/Decoder/BcBlockDecoder.cs#L21

Just leave a comment to help anyone reading the code understand what's happening.

**Comment by onepiecefreak3** [comment]
True. That would probably help there as well.

**Comment by onepiecefreak3** [comment]
As I could test, your alternative code is ok as is and was now added to my pending PR.

**Comment by onepiecefreak3** [comment]
@ptasev As this was solved with the last PR and your review of it, can this issue be closed?

**Comment by ptasev** [comment]
Seems good to me.
