### ISSUE TITLE
Tests for Bgra encode / decode

### ISSUE THREAD

**Issue by Nominom** [Nominom/BCnEncoder.NET#26]
Add tests for Bgra encode / decode for both dds and ktx (if ktx supports bgra).

**Comment by onepiecefreak3** [comment]
As far as my research went, KTX does not directly support BGRA. Therefore tests for it in ktx may not be possible, since it may not be possible to begin with.

**Comment by Nominom** [comment]
Ah, well that's a bummer. Might need to throw notsupportedexception if trying to encode to ktx then.

**Comment by Nominom** [comment]
Seems like there is an [extension](https://www.khronos.org/registry/OpenGL/extensions/APPLE/APPLE_texture_format_BGRA8888.txt) by apple that defines the Bgra GlInternalFormat enum. We can use that and write GlFormat as GL_BGRA. Real BGRA support without any extension would be in ktx2, if we ever decide to support that.
