### ISSUE TITLE
Discussion: remove ImageSharp? 

### ISSUE THREAD

**Issue by Nominom** [Nominom/BCnEncoder.NET#29]
As briefly discussed in #27 and #9,  removing imagesharp as a dependency is under consideration. This would require manual implememtation of a resizing algorithm. The main package api would be changed to use raw bytes or generics argument type. When supplied with a generic argument, the type would be blindly casted to an internal Rgba32 format. Here we cannot guarantee that the input data is in the right format. We could also implement Span2D support. 

Current ImageSharp api could be extracted to an extension package, that would add the current ImageSharp.Image based api.This would mainly be for convenience. We could also add an extension package for different image libraries, so the user is not locked to a single one.

What are your thoughts on such a change? Would it be more beneficial or harmful overall?

The benefits in my view are:
 - Not locked in to a single Image library
 - User has a choice to not use any external image library
 - We can add support for older .net versions

**Comment by Nominom** [comment]
Can also fix #10 at the same time, without waiting for the ImageSharp fix.

**Comment by onepiecefreak3** [comment]
Do we really want to support older .net versions? Imo, supporting older .net versions is not necessarily a benefit at all.
I can agree with the other two.
