### ISSUE TITLE
Improve readme.md example

### ISSUE THREAD

**Issue by HouseOfPandas** [Nominom/BCnEncoder.NET#52]
Hi,

I know I can be a bit dense, but it took me like 5 minutes to get the main page example working. I think it should include the "usings"

using BCnEncoder.ImageSharp; was specially hard, as for other usings you can right click and if you're lucky to have intellisense, it will help you, but with the BCnEncoder.ImageSharp one you have no idea what to search for... (I had to go check the tests to see what was different).

At least it works now, time for fun! :)

**Comment by Nominom** [comment]
Hi!

Thanks for the feedback. This is definitely something I overlooked since my own tooling handles usings quite automagically.

I'll add a mention of them in the examples.
