### ISSUE TITLE
Issues when encoding certain files to DDS

### ISSUE THREAD

**Issue by Hancapo** [Nominom/BCnEncoder.NET#53]
Hi, I've been working on a program that can create `.YTD` files from folders using images for Grand Theft Auto V.
Due to the game's nature, I need to convert the numerous image files to `.DDS` so I'm using BCnEncoder.NET for that, but I'm having serious issues with some images, one of my testers has some textures that was extracted from Assetto Corsa and some of those textures can't be encoded, I'm getting the following error:

![image](https://user-images.githubusercontent.com/20731612/153762190-3e64074d-7cc8-4937-a1ab-5825b1941ec8.png)

I already tried resaving the image (maintaining the same format) using Photoshop and Paint.NET and I even save it as `.TGA`

From a folder that has 34 textures just 30 of them were successfully converted to `.DDS`.
So I will attach those four textures as well: [crash.zip](https://github.com/Nominom/BCnEncoder.NET/files/8056045/crash.zip)

And this is the code I'm using to export the `.DDS`

```csharp
var amigo = bcEncoder.EncodeToDds(image); //Here's where the crash happens

MemoryStream ms = new();

amigo.Write(ms);

byte[] ddsbytes = ms.ToArray();


File.WriteAllBytes(Path.GetDirectoryName(filename) + "/" + GetImageName + ".dds", ddsbytes);
LbProgressLog.Dispatcher.Invoke(() => { LbProgressLog.AppendText($"\nDDS conversion of {Path.GetFileName(GetImageName)} was sucessful..."); });
```
Program details:

- .NET 6
- WPF
- Targeted for Windows7+

**Comment by Nominom** [comment]
Hi! 

Thanks for the detailed report. I tried it and got it to crash as well, but no idea what's causing it yet.

I'll investigate more tomorrow!

**Comment by Hancapo** [comment]
Many thanks!!, I really hope you can come out with a solution.

**Comment by Hancapo** [comment]
Hi, I've been troubleshooting the issue the entire afternoon and I discover the following:

- This happens with images bigger than 1024px either for their height or width. For example, a 1024x2048 PNG will crash.
- This happens with ANY format.
- I created a workaround where the image is resized, but it just works once, so if the image is 4096x4096 it will still crash since 2048 crashes the program.

**Comment by Nominom** [comment]
Looks like a new ImageSharp release broke my extension package. 

Images larger than 1024x1024 get allocated from a pool that contains buffers larger than the required size, which breaks things when trying to convert ImageSharp image memory to Memory2D. I should have a fix out in a couple of hours.

Thanks again for the report!

**Comment by Nominom** [comment]
New version of the extension package is up! 

https://www.nuget.org/packages/BCnEncoder.Net.ImageSharp/1.1.1

This should fix the issue you were having. If you find any other issues, please let me know.

**Comment by Maxxxel** [comment]
> Looks like a new ImageSharp release broke my extension package.
> 
> In the new version, images larger than 1024x1024 get allocated from a pool that contains buffers larger than the required size, which breaks things when trying to convert ImageSharp image memory to Memory2D. I should have a fix out in a couple of hours.
> 
> Thanks again for the report!

What about the  BCnEncoder45.NET  users :(

**Comment by Nominom** [comment]
Totally forgot about that.. I'll fix it as well. Should be done in about an hour

**Comment by Nominom** [comment]
Scratch that. There's no ImageSharp integration in that version so I can't really fix it.

@Maxxxel are you using ImageSharp and BcnEncoder.Net45 together in your own project?
The fix for me was to not use `Image.TryGetSinglePixelSpan`, and instead, just loop over the pixels row by row and column by column.

Something like this
```C#
for (var y = 0; y < img.height; y++)
{
        for (var x = 0; x < img.width; x++)
        {
	        var i = y * img.width + x;
	        img[x, y] = new Rgba32(decoded[i].r, decoded[i].g, decoded[i].b);
        }
}
```

**Comment by Maxxxel** [comment]
I was looking for a different solution and found a Paint.Net plugin I can load and use for bitmap->DDS. But thanks for your efforts❤️

**Comment by Nominom** [comment]
Glad you figured out a solution 🦊👍

If you do end up using BCnEncoder, don't hesitate to ask questions. I'll be glad to help
