### ISSUE TITLE
Add support for HDR textures with BC6H

### ISSUE THREAD

**Issue by Nominom** [Nominom/BCnEncoder.NET#8]

**Comment by onepiecefreak3** [comment]
Half-Precision Floating point: https://gist.github.com/vermorel/1d5c0212752b3e611faf84771ad4ff0d
Specification (similar to BC7): https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_texture_compression_bptc.txt

**Comment by Nominom** [comment]
Thanks for the links!
