### ISSUE TITLE
Upgrade ImageSharp dependency version

### ISSUE THREAD

**Issue by Nominom** [Nominom/BCnEncoder.NET#9]

**Comment by juliusfriedman** [comment]
Also consider an implementation without such; https://github.com/windows-toolkit/WindowsCommunityToolkit/blob/205eedfc930e62dd8e21c8a8df63a9e75ba4955f/Microsoft.Toolkit.HighPerformance/Memory/ReadOnlySpan2D%7BT%7D.cs

**Comment by Nominom** [comment]
Do you mean removing ImageSharp as a whole and switching to Span2D for the api, or just adding them as extra methods? I've been thinking of eventually removing ImageSharp, but I would need a way to load at least some basic image format (like png or tga). Mipmaps are also generated with ImageSharp but I guess implementing my own resizing wouldn't be too much of a task.

**Comment by juliusfriedman** [comment]
I would be willing to work with you on an Encoder / Decoder interface class which works with either Pipes, Sequences, Streams or whatever your preferred paradigm is; I had selected Stream for my previous such attempts for various reasons including Stream being able to read and write directly from such. The basic implementation of such would be light and there in allow for any type of encapsulated operation from a derived class. 

I hate to minimize it to such but all an Encoder / Decoder is just a way of getting data in or out of memory such that it conforms to the expected bit patterns, adding formats after that is super trivial.

I am not saying my implementation is the best (it can definitely be improved performance wise for example) but it tis very general and allows for quite contrived scenarios such as specially formatted data (BRAG) in which format the alpha embeds audio data as well as the bits required for transparency information...

Resizing is also `trival` given that the filtering and subsampling techniques are what provide better or worse such scales I would intuit that a few basic such scalers would be created (See MagikHarp or Gyrados.. .I don't have the links off hand) and that implementation would serve as a good enough. 

From there one can refine as much as required or implement an alternative such strategy using some of the components from adjacent parts of the image...

I am sure you know all this know and I waste my type inferring such....

May I infer, What do you see the biggest thing that ImageSharp provides you outside of the limited implementation of JPEG, PNG and GIF which it provides?

If that is all then just work on a basic implementation of those things and you have what you need...

I have the JPEG Part mostly in reader form, writing would be trivial... https://github.com/juliusfriedman/net7mma_core/blob/e7b228cfd6ce36401e11d1d1f31b29a4e9d41ba0/Codecs/Image/Jpeg/MarkerReader.cs

You are more than welcome to any of my code if it helps your project have less dependencies, you need not even bear the license where you got the code from if such makes it more palatable, I give thee full permissions. 

All I would ask is that I would be able to move more of the Codec stuff to a library where we both maintain it, there are many variations of all such media and thinking we can provide something to encompass all such is ... ambitious enough to be Ludacris as to type.

My library was never focuses on codecs, I just wanted to provide it would be able to to be done in ALL managed code if you had the ambition to do so.

Hopefully none of that came across wrong.

Thank you for your library and let me know if I can be of any assistance.

**Comment by Nominom** [comment]
I really like the idea of a Stream-based encoder/decoder class. If you're willing to help, I created an discussion issue for it in #27.  

ImageSharp is only used for the few basic formats and mipmap resizing. If I can implement my own Rgba32Image class that could at least do png and jpeg, then I can easily drop it as a dependency. Implementing a resizing algorithm is not an issue. 

I'm not sure what you mean by the brain-interfacing and implant stuff, but I'm assuming you mean to use the BcEncoder as some sort of compression layer between the implant and some other device? I'm interested in hearing more about your use-case.

**Comment by onepiecefreak3** [comment]
To be honest, how did the wall of text comment above talk about audio buffers, and abstract derivations for brain interlinks? This is BCn, and image compression. Nothing more, nothing less. What exactly do brain interfaces have to do with this in any way? Or audio for that matter?

**Comment by juliusfriedman** [comment]
Umm its the most basic type of transform.. hence why you want TGA support et al. Right?

**Comment by onepiecefreak3** [comment]
I think your ideas are way out of scope for this library, honestly. If you want to load TGA's and then decode the BC format in it, you can already do so. Just load the TGA with something else and decode its data with the DecodeRaw methods.
Also for which systems is Audio, Video? If you talk about systems that are not computers, I would like to reiterate, that such is out of scope for this library imo.
How the human brain seens and transforms images/data is also not really relevant to this specific library.

**Comment by Nominom** [comment]
There might have been a bit of a misunderstanding. Tga (truetype targa) is an image format commonly used for raw textures in games. It does not contain any audio to my knowledge.

**Comment by juliusfriedman** [comment]
> There might have been a bit of a misunderstanding. Tga (truetype targa) is an image format commonly used for raw textures in games. It does not contain any audio to my knowledge.

By default no it doesnt.

**Comment by juliusfriedman** [comment]
> I think your ideas are way out of scope for this library, honestly. If you want to load TGA's and then decode the BC format in it, you can already do so. Just load the TGA with something else and decode its data with the DecodeRaw methods.
> Also for which systems is Audio, Video? If you talk about systems that are not computers, I would like to reiterate, that such is out of scope for this library imo.
> How the human brain sees and transforms images/data is also not really relevant to this specific library.

Dually noted and summarily overruled when I hear from @Nominom it will be different.

If you have any more questions let me know.

good day

**Comment by juliusfriedman** [comment]
> I really like the idea of a Stream-based encoder/decoder class. If you're willing to help, I created an discussion issue for it in #27.
> 
> ImageSharp is only used for the few basic formats and mipmap resizing. If I can implement my own Rgba32Image class that could at least do png and jpeg, then I can easily drop it as a dependency. Implementing a resizing algorithm is not an issue.
> 
> I'm not sure what you mean by the brain-interfacing and implant stuff, but I'm assuming you mean to use the BcEncoder as some sort of compression layer between the implant and some other device? I'm interested in hearing more about your use-case.

PNG? JPEG? Done. I mean both have been done to death in various forms depending on the profile and amount of proprietary extension you want to support... 

I doubt you would need the writer but I intuit so much.

Thank you for your time and comments!
